---

- name: Gather hetzner dns zones
  ansible.builtin.uri:
    url: "{{ hetzner_dns_api_url }}/zones"
    headers:
      Auth-API-Token: "{{ hetzner_dns_api_token }}"
  delegate_to: localhost
  register: output

- name: Print hetzner dns zones
  ansible.builtin.debug:
    msg: "{{ output.json.zones }}"
  when: hetzner_dns_debug

- name: Set fact _hetzner_dns_zone_ids
  ansible.builtin.set_fact:
    _hetzner_dns_zone_ids: "{{ output.json.zones | items2dict(key_name='name', value_name='id') }}"

- name: Set fact _hetzner_dns_zone_id
  ansible.builtin.set_fact:
    _hetzner_dns_zone_id: "{{ _hetzner_dns_zone_ids[hetzner_dns_zone_name] }}"

- name: Gather hetzner dns zone records for "{{ _hetzner_dns_zone_id }}"
  ansible.builtin.uri:
    url: "{{ hetzner_dns_api_url }}/records?zone_id={{ _hetzner_dns_zone_id }}"
    headers:
      Auth-API-Token: "{{ hetzner_dns_api_token }}"
  delegate_to: localhost
  register: output

- name: Print hetzner zone records of "{{ _hetzner_dns_zone_id }}"
  ansible.builtin.debug:
    msg: "{{ output.json.records }}"
  when: hetzner_dns_debug

- name: Set fact _hetzner_dns_records for "{{ _hetzner_dns_zone_id }}"
  ansible.builtin.set_fact:
    _hetzner_dns_records: "{{ output.json.records }}"

- name: Print _hetzner_dns_records for "{{ _hetzner_dns_zone_id }}"
  ansible.builtin.debug:
    msg: "{{ _hetzner_dns_records }}"
  when: hetzner_dns_debug

- name: Set fact _hetzner_dns_record_id for "{{ hetzner_dns_record_name }}", "{{ hetzner_dns_record_type }}"
  ansible.builtin.set_fact:
    _hetzner_dns_record_id: "{{ _hetzner_dns_records 
      | selectattr('name', 'equalto', hetzner_dns_record_name)
      | selectattr('type', 'equalto', hetzner_dns_record_type)
      | map(attribute='id')
      | list
    }}"

- name: Print number of elements in _hetzner_dns_record_id
  ansible.builtin.debug:
    msg: "{{ _hetzner_dns_record_id | length }}"
  when: hetzner_dns_debug

- name: Set fact _hetzner_dns_record_id_exact for "{{ hetzner_dns_record_name }}", "{{ hetzner_dns_record_type }}", "{{ hetzner_dns_record_value }}", "{{ hetzner_dns_record_ttl }}"
  ansible.builtin.set_fact:
    _hetzner_dns_record_id_exact: "{{ _hetzner_dns_records 
      | selectattr('name', 'equalto', hetzner_dns_record_name)
      | selectattr('type', 'equalto', hetzner_dns_record_type)
      | selectattr('value', 'equalto', hetzner_dns_record_value)
      | selectattr('ttl', 'equalto', hetzner_dns_record_ttl)
      | map(attribute='id')
      | list
    }}"

- name: Print number of elements in _hetzner_dns_record_id_exact
  ansible.builtin.debug:
    msg: "{{ _hetzner_dns_record_id_exact | length }}"
  when: hetzner_dns_debug

- name: Print hetzner_dns_record_create_or_delete
  ansible.builtin.debug:
    msg: "{{ hetzner_dns_record_create_or_delete }}"
  when: hetzner_dns_debug

- name: Create hetzner dns record
  ansible.builtin.uri:
    url: "{{ hetzner_dns_api_url }}/records"
    body_format: json
    headers:
      Auth-API-Token: "{{ hetzner_dns_api_token }}"
    method: post
    body:
      zone_id: "{{ _hetzner_dns_zone_id }}"
      name: "{{ hetzner_dns_record_name }}"
      type: "{{ hetzner_dns_record_type }}"
      value: "{{ hetzner_dns_record_value }}"
      ttl: "{{ hetzner_dns_record_ttl }}"
  delegate_to: localhost
  when: (_hetzner_dns_record_id | length) <= 0
          and not hetzner_dns_record_delete
  changed_when: true

- name: Update hetzner dns record
  ansible.builtin.uri:
    url: "{{ hetzner_dns_api_url }}/records/{{ _hetzner_dns_record_id[0] }}"
    body_format: json
    headers:
      Auth-API-Token: "{{ hetzner_dns_api_token }}"
    method: put
    body:
      zone_id: "{{ _hetzner_dns_zone_id }}"
      name: "{{ hetzner_dns_record_name }}"
      type: "{{ hetzner_dns_record_type }}"
      value: "{{ hetzner_dns_record_value }}"
      ttl: "{{ hetzner_dns_record_ttl }}"
  delegate_to: localhost
  when: (_hetzner_dns_record_id | length) == 1 
          and (_hetzner_dns_record_id_exact | length) <= 0 
          and not hetzner_dns_record_delete
  changed_when: true

- name: Delete hetzner dns record
  ansible.builtin.uri:
    url: "{{ hetzner_dns_api_url }}/records/{{ _hetzner_dns_record_id[0] }}"
    headers:
      Auth-API-Token: "{{ hetzner_dns_api_token }}"
    method: delete
  delegate_to: localhost
  when: (_hetzner_dns_record_id | length) == 1 
          and (_hetzner_dns_record_id_exact | length) == 1
          and hetzner_dns_record_delete
  changed_when: true

...