---

- name: Gather hetzner dns zones
  ansible.builtin.uri:
    url: "{{ hetzner_dns_api_url}}/zones"
    headers:
      Auth-API-Token: "{{ hetzner_dns_api_token }}"
  delegate_to: localhost
  register: output

# - name: Print hetzner dns zones
#   ansible.builtin.debug:
#     msg: "{{ output.json.zones }}"

- name: Set fact _hetzner_dns_zone_ids
  ansible.builtin.set_fact:
    _hetzner_dns_zone_ids: "{{ output.json.zones | items2dict(key_name='name', value_name='id') }}"

- name: Set fact _hetzner_dns_zone_id
  ansible.builtin.set_fact:
    _hetzner_dns_zone_id: "{{ _hetzner_dns_zone_ids[hetzner_dns_zone_name] }}"

# - name: Print hetzner zone id of {{ hetzner_dns_zone_name }}
#   ansible.builtin.debug:
#     msg: "hcloud_zone_id: {{ hetzner_dns_zone_id }}"

- name: Gather hetzner dns zone records for {{ hetzner_dns_zone_id }}
  ansible.builtin.uri:
    url: "{{ hetzner_dns_api_url}}/records?zone_id={{ _hetzner_dns_zone_id }}"
    headers:
      Auth-API-Token: "{{ hetzner_dns_api_token }}"
  delegate_to: localhost
  register: output

# - name: Print hetzner zone records of {{ _hetzner_dns_zone_id }}
#   ansible.builtin.debug:
#     msg: "{{ output.json.records }}"

- name: Set fact _hetzner_dns_records for {{ _hetzner_dns_zone_id }}
  ansible.builtin.set_fact:
    _hetzner_dns_records: "{{ output.json.records }}"

- name: Set fact _hetzner_dns_record_id for {{ hetzner_dns_record_name }}, {{ hetzner_dns_record_type }}
  ansible_builtin.set_fact:
    _hetzner_dns_record_id: "{{ _hetzner_dns_records 
      | selectattr('name', 'equalto', hetzner_dns_record_name)
      | selectattr('type', 'equalto', hetzner_dns_record_type)
      | map(atrribute='id')
      | list
      | first
      | default('not found')
    }}"

- name: Create hetzner dns record
  ansible.builtin.uri:
    url: "{{ hetzner_dns_api_url}}/records"
    body_format: json
    headers:
      Auth-API-Token: "{{ hetzner_dns_api_token }}"
    method: post
    body:
      zone_id: "{{ _hetzner_dns_zone_id }}"
      name: "{{ hetzner_dns_record_name }}"
      type: "{{ hetzner_dns_record_type }}"
      value: "{{ hetzner_dns_record_value }}"
      ttl: "{{ hetzner_dns_record_ttl }}"
  delegate_to: localhost
  when: _hetzner_dns_record_id == 'not found'

- name: Update hetzner dns record
  ansible.builtin.uri:
    url: "{{ hetzner_dns_api_url}}/records/{{ _hetzner_dns_record_id }}"
    body_format: json
    headers:
      Auth-API-Token: "{{ hetzner_dns_api_token }}"
    method: put
    body:
      zone_id: "{{ _hetzner_dns_zone_id }}"
      name: "{{ hetzner_dns_record_name }}"
      type: "{{ hetzner_dns_record_type }}"
      value: "{{ hetzner_dns_record_value }}"
      ttl: "{{ hetzner_dns_record_ttl }}"
  delegate_to: localhost
  when: _hetzner_dns_record_id != 'not found'

...